version = 1

test_patterns = [
  "**/tests/**",
  "**_test.py"
]

exclude_patterns = ["**/migrations/**"]

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"