version: "3.9"

name: enfight-api

services:
  web:
    image: dimadk24/enfight-api:latest
    build:
      context: .
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    pull_policy: never
    env_file: docker.env
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file: docker.env
    restart: unless-stopped
    healthcheck:
        # https://stackoverflow.com/a/75794612
        test: "exit | mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD"
        interval: 2s
        timeout: 20s
        retries: 10

  redis:
    image: redis:6
    restart: unless-stopped

volumes:
  mysql-data:
